### ISSUE TITLE
Module typing_extensions not found

### ISSUE THREAD

**Issue by pabloignaciolerner** [pyedifice/pyedifice#101]
Hello. I wanted to test pyedifice so I installed doing `pip install pyedifice`. Then I copied and tried to run the attached example found on the web, but got an error `ModuleNotFoundError: No module named 'typing_extensions'`. Is it possible to add to PYPI all module dependencies so that PIP would automatically install them?

I am using:
 Windows 11
python 3.12
virtual environment created using venv in standard library

Modules installed:
pyedifice 0.3.2
PySide6 6.6.1

![imagen](https://github.com/pyedifice/pyedifice/assets/85712275/f95614e7-8a18-4887-b58c-16b4515ca1cc)

**Comment by jamesdbrock** [comment]
Yeah good point. Thanks for opening this issue.

**Comment by jamesdbrock** [comment]
Published v0.3.3 https://pyedifice.github.io/versions.html

**Comment by pabloignaciolerner** [comment]
Thanks!
