### ISSUE TITLE
Window opens small

### ISSUE THREAD

**Issue by jamesdbrock** [pyedifice/pyedifice#115]
The Window opens very small now.

I think this is happening since https://github.com/pyedifice/pyedifice/commit/28c07eb6c8f00046fd1b8af3d42c607cde8f8bf5

Maybe because the Window now `show()`s before the other Qt commands are run for the component tree?

**Comment by sachitotakahashi-vienna** [comment]
Usually, Windows application will remember the size when it was closed the last time and will be opened in the same size.
Isn't it possible to take that information from the registry?

**Comment by jamesdbrock** [comment]
Fixed in v2.1.0 https://pyedifice.github.io/versions.html#v2-1-0
