### ISSUE TITLE
'app.export_widgets()' Runtime error?

### ISSUE THREAD

**Issue by matkuki** [pyedifice/pyedifice#132]
Hi,

Specs:
- Windows 10 x64
- Python 3.10.11
- PyQt 6.6.1
- Edifice 0.5.1 (installed from PyPI)

I modified the `Calculator` example with this:
```python
if __name__ == "__main__":
    app = ed.App(Main())
    widget = app.export_widgets()
    app.start()
```
... to be able to integrate it into another PyQt6 application, but this now throws an error:
```
Traceback (most recent call last):
  File "E:\Python\pyedifice\testing\testing.py", line 145, in <module>
    widget = app.export_widgets()
  File "C:\Python310\lib\site-packages\edifice\app.py", line 331, in export_widgets
    raise RuntimeError("The root element of the App for export_widgets() must be an ExportList")
RuntimeError: The root element of the App for export_widgets() must be an ExportList
```
Am I missing something?
Thanks

**Comment by jamesdbrock** [comment]
Hi @matkuki .

With the `App` you can `start()` it, or `export_widgets()`, but not both.

If you want to `export_widgets()` then you should not `start()` the `App`. The exported widgets will be reactive and stateful. Like so: https://pyedifice.github.io/stubs/stubs/edifice.App.export_widgets.html

**Comment by matkuki** [comment]
Ah, thanks for the explanation 👍
