### ISSUE TITLE
Add message box widgets

### ISSUE THREAD

**Issue by adigitoleo** [pyedifice/pyedifice#14]
For example, enaml has 'about', 'critical', 'information', 'question', and 'warning' functions that display an appropriate message box popup. Possibly relies on resolving #11, as they need to be in a separate window. In my opinion these are as important as the grid layout. It seems logical to use the Qt Dialog class for this:

https://doc.qt.io/qt-5/qdialog.html

**Comment by fding** [comment]
Agreed. I'll get around to adding these.

**Comment by jamesdbrock** [comment]
We now have `WindowPopView` in v1.5.0 https://pyedifice.github.io/versions.html#v1-5-0
