### ISSUE TITLE
Outdated tutorial

### ISSUE THREAD

**Issue by hoel-bagard** [pyedifice/pyedifice#143]
I'm not sure if that's the right place to post this, but the PyEdifice [tutorial on GitHub](https://pyedifice.github.io/tutorial.html) and the one [on the PyEdifice website](https://www.pyedifice.org/tutorial) do not match.

Notably, the installation instructions on the website are not up to date, meaning that anyone trying to follow the tutorial would face an installation error right from the start.

**Comment by jamesdbrock** [comment]
As I think you noticed, that is the old website. The new website is https://pyedifice.github.io/

**Comment by hoel-bagard** [comment]
Yes, and I heard from Viktor that you sadly don't have control over the old one.
