### ISSUE TITLE
Make Element constructor side-effect free

### ISSUE THREAD

**Issue by considerate** [pyedifice/pyedifice#149]
Currently `edifice` is highly reliant on the side effect in the constructor of an `Element` that adds itself to the most recent `Tracker` in the context. This means that elements aren't first-class objects that can be passed to combinators and the like.

That is in the current example:
```python
with View(layout="column"):
    Label("First Label")
    Label("Second Label")
    with ButtonView(layout="row"):
        Label("Button Label")
	Label("Third Label")
```

The `Labels` are attached to most recent `Tracker` generated by the context managers (`with` statements) when they are constructed. This means that you cannot store an `Element` in a variable and then apply it to a parent `Element`.

I propose we remove the side-effect from the constructor and instead create a specialized function, let's call the function `child` for the purposes of this discussion. The above example could now be updated to:

```python
second_label = Label("Second Label")
with View(layout="column"):
    child(Label("First Label"))
    child(second_label)
    with child(ButtonView(layout="row")):
        child(Label("Button Label"))
	child(Label("Third Label"))
```

Note that in order for the `ButtonView` to act as a context manager the `child` function has the return the element. Alternatively, the `child` function itself is what generates the tracker and the example would be updated to:

```python
second_label = Label("Second Label")
with child(View(layout="column")):
    child(Label("First Label"))
    child(second_label)
    with child(ButtonView(layout="row")):
        child(Label("Button Label"))
	child(Label("Third Label"))
```

**Comment by jamesdbrock** [comment]
For each Qt Element like `Label`, we should provide a convenience function `rLabel = child(Label)`.

```python
with View(layout="column")
    rLabel("First label")
```

**Comment by considerate** [comment]
```python
child(View())(Label("first"), Label("second"))
```

**Comment by considerate** [comment]
```python
with child(View()) as tracker:
    tracker.add(Label("asd"))
```

**Comment by considerate** [comment]
Decision the above mentioned `child` helper should be called `render` because it's a verb which is more in line with the side-effectful "statement" semantics of this.

**Comment by considerate** [comment]
Maybe the `render` function is not a function after all, it could be a method on the `Element` class.
