### ISSUE TITLE
Shallow copy in `use_state`

### ISSUE THREAD

**Issue by considerate** [pyedifice/pyedifice#151]
Since the users have to create a shallow for the `__eq__` check in `use_state` to be sensible we might as well just create a [shallow copy](https://docs.python.org/3/library/copy.html#copy.copy) of the state variable so that the user doesn't have to copy the object themselves.

**Comment by jamesdbrock** [comment]
This is a good idea but I'm inclined to not do it. I think it's less confusing when we expose all this machinery explicitly and explain what's happening.

**Comment by jamesdbrock** [comment]
React forces the users to understand and use shallow-copy https://react.dev/learn/updating-arrays-in-state

When in doubt, I like to do it the way React does it.
