### ISSUE TITLE
Nothing is displayed

### ISSUE THREAD

**Issue by tjtuom** [pyedifice/pyedifice#16]
Hi,

When I run any of the examples in the docs I never get anything displayed on the screen. I don't get any errors logged and I see the python app spawning but macos says it's not responding. Top shows it using 100% of CPU and I need to kill it to get it to stop. I have tried it with both PySide2 and PyQt5 with the same results. The plain Qt example you have works fine.

Any ideas?

**Comment by tjtuom** [comment]
I managed to solve it by just importing QtWidgets at the top of the file. I don't even have the environment variable set. Importing PySide2 has no effect.

**Comment by fding** [comment]
That's odd. I'll try to get my hands on a Windows machine so I can do more proper testing there.

**Comment by tjtuom** [comment]
I was using MacOS big sur.
