### ISSUE TITLE
Tracker render() method alias functions

### ISSUE THREAD

**Issue by jamesdbrock** [pyedifice/pyedifice#164]
Instead of #162 , we could keep the `Tracker` and the `Element.render()` methods and add an alias function like `label(*props) = Label(*props).render()` for each element which would look like:

```python
with view():
  label("one")
  label("two")
  with button_view(on_trigger=handle_trigger):
    label("three")
```

What to do about `@component` elements though?

**Comment by jamesdbrock** [comment]
What to do about `@component` elements though? If we have

```python
@component
def MyComponent(self, prop1):
```

then `MyComponent` is either
- just a class that inherits from `Element`, so you have to call `MyComponent.render()`
- a function which creates a `MyComponent` and calls `render()`.

**Comment by JoanCoCo** [comment]
I am not sure if this really solves the issue, but what about defining 2 decorators? One is or regular component to get an `ed.Element`, and another is used to wrap the ed.Element into a function that is equivalent to the `ed.Element(*props).render()`. Then you can wrap both decorations into a single one.

**Comment by JoanCoCo** [comment]
Something like:
```python
...

def component_wrapper(f: Callable[tp.Concatenate[selfT, P], None]) -> Callable[P, Tracker]:
    return render_object(component(f))

def render_object(f: Callable[P, Element]) -> Callable[P, Tracker]:
    def _inner(**p: tp.Any) -> Tracker:
        return f(**p).render
    return _inner
    
def component ...  # This one remains as is.
```

Then you could define my component as:

```python
@component_wrapper
def MyComponent(self, prop1):
    ...
```

So you can:

```python
with view():
    label("one")
    label("two")
    with button_view(on_trigger=handle_trigger):
        MyComponent("hello there")
```

Again, maybe I am not seeing the full picture here, but that works in my head (with better naming for the decorators...).

**Comment by jamesdbrock** [comment]
> but what about defining 2 decorators? One is or regular component to get an `ed.Element`, and another is used to wrap the ed.Element into a function that is equivalent to the `ed.Element(*props).render()`. Then you can wrap both decorations into a single one. 

I have thought about your example and I don't understand how it works? But if it works then it sounds great.

With your example, the name `MyComponent` binds to only the `MyComponent().render()` call right? There is still no way to call the plain `MyComponent()` constructor?
