### ISSUE TITLE
TabView seems to be broken

### ISSUE THREAD

**Issue by masc-it** [pyedifice/pyedifice#187]
Hey,

i am trying to use TabView, but it's not working for some reason. I have this very simple code:

```
with ed.TabView(labels=["Section1", "section2"]):
            with ed.VBoxView():
                ed.Label("HEY")
            with ed.VBoxView():
                ed.Label("HEY...")
```
When I run this all I have is a grey container and nothing shows up.. any clues?

**Comment by jamesdbrock** [comment]
Thanks for opening this issue, I'll investigate.

**Comment by jamesdbrock** [comment]
Yeah there was `assert` bug which was raising an exception. I just published [v2.4.0](https://pyedifice.github.io/versions.html#v2-4-0) which fixes the bug.

**Comment by jamesdbrock** [comment]
No-one ever uses or tests this `TabView` element because in reactive declarative programming it's so easy to destroy and create whole sections of the user interface. Generally I prefer to destroy a section of user interface instead of hiding it. But I guess there are cases where `TabView` is useful.

What would be nice in the future is a `TabView` element which is not a layout `View`, but rather is just radio buttons rendered graphically as tabs.

**Comment by masc-it** [comment]
I see, makes sense thanks for explaining.

I am implementing a bottom bar navigation menu, I can share here if you want! It's a great excercise to know pyedifice better!

I am having a wonderful experience till now btw (I've past experience in various js frameworks), I'm just finding some rough edges with dynamic / flex layouts (e.g. it would be super comfy to have the current window / parent shapes somewhere, ready to access, rather than using vref and all that boilerplate).

**Comment by jamesdbrock** [comment]
> I am implementing a bottom bar navigation menu, I can share here if you want! It's a great excercise to know pyedifice better!

Yeah cool if you publish it somewhere I'd like to see it please.

> I am having a wonderful experience till now btw (I've past experience in various js frameworks), 

Glad to hear it.

> I'm just finding some rough edges with dynamic / flex layouts (e.g. it would be super comfy to have the current window / parent shapes somewhere, ready to access, rather than using vref and all that boilerplate) but I guess this is for another issue lol.

Yeah the Qt layout engine is full of surprising differences from the Webkit layout engine. Do you want to do calculations based on the sizes of elements? For that try passing an event handler to the [`on_resize` prop](https://pyedifice.github.io/stubs/edifice.QtWidgetElement.html) and then setting a `use_state` variable in the `on_resize` event handler.
