### ISSUE TITLE
keyboard, `space bar` or `enter` cannot trigger a button clicking

### ISSUE THREAD

**Issue by mo-han** [pyedifice/pyedifice#20]
pressing `space bar` when focusing on a button will trigger an animation of button click, but the button's `on_click` is not called, have to use mouse to do a "real click"

while pressing `enter` cannot even generate a button clicked animation

p.s. this project has very promising future, but current version still very incomplete, i would hope to be more skillful to contribute to this project but right now i'm a newbie especially in Qt

**Comment by fding** [comment]
Hi, thank you for your feedback and suggestions. Please keep on filing feature requests so that I have a better idea of what people want or need in their projects.

I'll take a look at keyboard bindings and figure out the best way to incorporate them.

**Comment by jamesdbrock** [comment]
I've confirmed this that <kbd>Space</kbd> and <kbd>Enter</kbd> do not fire `QPushButton.clicked()`, which is strange because the docs say they do.

https://doc.qt.io/qtforpython-6/PySide6/QtWidgets/QPushButton.html#detailed-description

> A push button emits the signal [clicked()](https://doc.qt.io/qtforpython-6/PySide6/QtWidgets/QAbstractButton.html#PySide6.QtWidgets.PySide6.QtWidgets.QAbstractButton.clicked) when it is activated by the mouse, the Spacebar or by a keyboard shortcut.

**Comment by jamesdbrock** [comment]
Ah It’s because edifice is using `mousePressEvent`.

https://github.com/fding/pyedifice/blob/53007e112912d870c9202e14c9d8a0884d83bf24/edifice/base_components.py#L313-L323

**Comment by jamesdbrock** [comment]
I tried to solve this by making the `on_click` prop use the [`clicked()`](https://doc.qt.io/qtforpython-6/PySide6/QtWidgets/QAbstractButton.html#PySide6.QtWidgets.PySide6.QtWidgets.QAbstractButton.clicked) signal but it didn't work because two events would get raised for a single mouse click.

So I tried this other way and this works, but it uses a different `on_trigger` prop.


```python

    @register_props
    def __init__(self,
            layout: str = "row",
            on_trigger: tp.Optional[tp.Callable[[tp.Any], None]] = None,
            **kwargs):
        super().__init__(layout, **kwargs)
```

```python
    def _set_on_trigger(self, underlying, on_trigger):
        if on_trigger is not None:
            def on_click(ev:QMouseEvent):
                on_trigger()
            def on_key(ev:QKeyEvent):
                if ev.text() == ' ' or ev.text() == '\r':
                    on_trigger()
            self._set_on_click(underlying, on_click)
            self._set_on_key_up(underlying, on_key)

    def _qt_update_commands(self, children, newprops, newstate):
        if self.underlying is None:
            self._initialize()
        commands = super()._qt_update_commands(children, newprops, newstate)
        for prop in newprops:
            if prop == "on_trigger":
                commands.append((self._set_on_trigger, self.underlying, newprops.on_trigger))
        return commands
```

**Comment by jamesdbrock** [comment]
The `ButtonView` component which has an `on_trigger` prop that handles both key press and mouse clicks is now published as part of Edifice. https://pyedifice.github.io/stubs/edifice.components.button_view.ButtonView.html

We should think about how we want to generally handle this problem with the Base `Button` too.

**Comment by jamesdbrock** [comment]
The best solution is to use [`ButtonView`](https://pyedifice.github.io/stubs/edifice.ButtonView.html)
