### ISSUE TITLE
PySide2 dependency prevents installation on macOS with Apple Silicon

### ISSUE THREAD

**Issue by MatuaDoc** [pyedifice/pyedifice#24]
PySide2 is not officially supported on M1-based machines and no package for it exists for arm64 on macOS. Therefore, Edifice cannot be installed through pip even if one only wants to use the PyQt5 backend.

**Comment by fding** [comment]
Thanks for flagging. You can install Edifice without dependencies using these commands:

pip install watchdog  # A dependency required for dynamic reloads
pip install qasync  # A dependency required for asyncio integration
pip install --no-dependencies pyedifice

and by setting the EDIFICE_QT_VERSION environment variable to PyQt5.
