### ISSUE TITLE
WebGL/JS/Web support

### ISSUE THREAD

**Issue by fire17** [pyedifice/pyedifice#25]
Hi guys! Just came across this project and I really love the concept
Do you think that you could also render to some web framework ?
Then I can design my app once, and either run it locally or host it as a site with the same visual core code

Could be super useful 
Love how you have dynamic bindings 
Would love to have these features on the browser

**Comment by fding** [comment]
It would indeed be interesting to support other backends such as for the web. Currently, I don't have plans to add it any time soon, but pull requests are welcome :)
