### ISSUE TITLE
Running edifice in a asyncio loop

### ISSUE THREAD

**Issue by mstarongithub** [pyedifice/pyedifice#29]
Hello,

I'd like to know if there is a method for me to run an Edifice application in an event loop from AsyncIO? I'd need this to avoid workarounds for a project I am working on in which I would ideally like to utilize TwitchIO for a chat bot and Edifice as a front end to control said bot. 

Judging from the code of `App.start()` I would assume that that should be possible, but I didn't find a good method to do so. Any insights?

**Comment by MrEvilOnGitHub** [comment]
Update: Did a quick test and I was able to successfully run async code when starting the app using a modifed copy of the start function.

The modified version in question: ```python
    def run_with_async(self, task): # task is the coroutine to run next to edifice
        self._request_rerender([self._root], {})
        if self._inspector:
            logger.info("Running inspector")
            def cleanup(e):
                self._inspector_component = None

            self._inspector_component = inspector.Inspector(
                self._render_engine._component_tree, self._root,
                refresh=(lambda: (self._render_engine._component_tree, self._root)))
            icon_path = os.path.join(os.path.abspath(os.path.dirname(__file__)), "inspector/icon.png")
            component = Window(title="Component Inspector", on_close=cleanup, icon=icon_path)(self._inspector_component)
            component._edifice_internal_parent = None
            self._request_rerender([component], {})

        loop = QEventLoop(self.app)
        asyncio.set_event_loop(loop)
        with loop:
            loop.create_task(task()) # Added this
            ret = loop.run_forever()
        self._render_engine._delete_component(self._root, True)
        return ret
```

I tested this by passing the following method as second argument: ```python
async def timed_print():
    while True:
        await asyncio.sleep(5)
        print("Hello")
```
And as expected it printed out "Hello" every 5 seconds

**Comment by jamesdbrock** [comment]
Note: we need more discussion of how to use asyncio in the docs https://pyedifice.github.io/

**Comment by jamesdbrock** [comment]
It might also make sense to change the `App.start()` function to take a loop argument.

```python
def start(self, loop : AbstractEventLoop | None = None)
```

https://github.com/pyedifice/pyedifice/blob/39f499b271b1dae27eac26c8064eb89feed393c2/edifice/app.py#L255

**Comment by jamesdbrock** [comment]
I think in your case it would be best to [`create_task`](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task) after your app mounts.

```python
async def timed_print():
    while True:
        await asyncio.sleep(5)
        print("Hello")
```
```python
class MyComponent(ed.Component):

    background_tasks = set()

    def did_mount(self):
        task = asyncio.create_task(timed_print())
        background_tasks.add(task)
        task.add_done_callback(background_tasks.discard)
```
```python
App(MyComponent()).start()
```

**Comment by jamesdbrock** [comment]
The docs discuss how to run async event handlers. https://pyedifice.github.io/base_components.html#events
