### ISSUE TITLE
pyqtgraph integration

### ISSUE THREAD

**Issue by fakuivan** [pyedifice/pyedifice#30]
[pyqtgraph](https://www.pyqtgraph.org/) is much faster than matplotlib for live graphs. I need this for oscilloscope like functionality I want to put into an app, the overhead caused by matplotlib is quite prohibitive, and the extra functionality is not needed in this case. How would a rough implementation using `CustomWidget` look like?

**Comment by jamesdbrock** [comment]
This `function_component` from @fakuivan looks very nice https://github.com/fakuivan/py-fast-plotting/blob/master/ed_utils/misc.py

**Comment by jamesdbrock** [comment]
I've added a beta-version PyQtGraph Plot component https://github.com/pyedifice/pyedifice/blob/9d0b7bc717728b15be46a23f0d6ca3ce3df63d4b/edifice/components/pyqtgraph_plot.py

with this example https://github.com/pyedifice/pyedifice/blob/9d0b7bc717728b15be46a23f0d6ca3ce3df63d4b/examples/example_pyqtgraph.py

which renders like this 
![image](https://github.com/pyedifice/pyedifice/assets/1526224/2396a23c-9ea9-486e-8797-f60566a5da50)
