### ISSUE TITLE
TextInput active prop

### ISSUE THREAD

**Issue by powerbling** [pyedifice/pyedifice#31]
How to inactivate a TextInput?
`TextInput('---', active=False)`
Tried this way but active is not an allowed argument.

**Comment by jamesdbrock** [comment]
Hm that `active` prop should probably be in https://pyedifice.github.io/stubs/edifice.QtWidgetComponent.html

**Comment by jamesdbrock** [comment]
Add the `enabled` prop to all `QtWidgetElement`s.

https://github.com/pyedifice/pyedifice/blob/9d0b7bc717728b15be46a23f0d6ca3ce3df63d4b/edifice/base_components/base_components.py#L238

This will be published with the next version.
