### ISSUE TITLE
watchdog omitted in requirements.txt

### ISSUE THREAD

**Issue by dhnam** [pyedifice/pyedifice#45]
Module `watchdog` is needed in dynamical reloading, but is omitted in requirements.txt.

**Comment by jamesdbrock** [comment]
>  watchdog is not installed with it, so I had to manually install it via pip.

That seems like a good solution? Or we could have a dev-requirements.txt? https://stackoverflow.com/questions/63243532/how-to-avoid-putting-dev-packages-in-requirements-txt

**Comment by dhnam** [comment]
Guess adding 'You should install watchdog to use dynamic reload' in readme.txt and tutorial about dynamic reload would be good way to go, I believe (when avoiding adding watchdog to requirement.txt)?
