### ISSUE TITLE
new component element and hot-reloading

### ISSUE THREAD

**Issue by jamesdbrock** [pyedifice/pyedifice#74]
The new `@component` elements don't work with hot reloading.

```
Encountered exception while reloading: Error while reloading <MyApp id=0x7fffdbac48e0  />: New class expects prop (args) not present in old class
Traceback (most recent call last):
  File "/home/jbrock/work/oth/pyedifice/pyedifice/edifice/app.py", line 157, in event
    render_result = self._render_engine._refresh_by_class(classes)
  File "/home/jbrock/work/oth/pyedifice/pyedifice/edifice/engine.py", line 451, in _refresh_by_class
    raise ValueError(
Stemming from these renders:
ValueError: Error while reloading <MyApp id=0x7fffdbac48e0  />: New class expects prop (args) not present in old class
```

I think it has something to do with this.

https://github.com/pyedifice/pyedifice/blob/14ba4713a632e2e8a88735e78d8d4dcd154fb301/edifice/_component.py#L660-L665

**Comment by jamesdbrock** [comment]
To see hot reloading succeed and fail, check out branch __hotreload1__ which restores the old example tutorial program.

Hot reloading works:

```
python -m edifice examples/tutorial.py MyApp
```

Hot reloading doesn't work:

```
python -m edifice examples/tutorial_old.py MyApp
```

**Comment by considerate** [comment]
My immediate thought is that this might be related to the `children` prop

**Comment by jamesdbrock** [comment]
When hot reloading the new `tutorial.py` on this line

https://github.com/pyedifice/pyedifice/blob/14ba4713a632e2e8a88735e78d8d4dcd154fb301/edifice/engine.py#L444

We have

```python
old_comp.props = PropsDict({'children': []})
```
and
```python
parameters = [
0: ('self', <Parameter "self">)
1: ('args', <Parameter "*args: P.args">)
2: ('kwargs', <Parameter "**kwargs...P.kwargs">)
```

So we get `Exception has occurred: KeyError 'args'`.

When hot reloading the `tutorial_old.py` on that line

```python
parameters = [('self', <Parameter "self">)]
```

**Comment by jamesdbrock** [comment]
This is the hard part. We mus somehow construct a new Element, using the props of the old Element. It doesn't have to be the right props, because we can just assign the right props on the next line after the Element is constructed. But constructing it is tricky.

https://github.com/pyedifice/pyedifice/blob/14ba4713a632e2e8a88735e78d8d4dcd154fb301/edifice/engine.py#L455
